#use_frameworks!

platform :ios, '9.0'

target 'DBFileSynchronizer_Example' do
  pod 'DBFileSynchronizer', :path => '../'

  target 'DBFileSynchronizer_Tests' do
    inherit! :search_paths

    
  end
end
